[package]
name = "nft_contract"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh.workspace = true
near-sdk.workspace = true
near-sdk-macros.workspace = true
serde.workspace = true
serde_json.workspace = true

[lib]
crate-type = ["cdylib"]
