[package]
name = "calimero-server"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
axum.workspace = true
async-graphql = { workspace = true, optional = true }
async-graphql-axum = { workspace = true, optional = true }
eyre.workspace = true
futures-util = { workspace = true, optional = true }
multiaddr.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true

calimero-runtime = { path = "../runtime" }
calimero-primitives = { path = "../primitives" }

[[example]]
name = "demo"

[dev-dependencies]
color-eyre.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[features]
graphql = ["dep:async-graphql", "dep:async-graphql-axum", "dep:futures-util"]
